In [1]:
import pandas as pd
import numpy as np

print("Libraries imported successfully! ✅")

Libraries imported successfully! ✅

In [2]:
df = pd.read_csv("../data/processed/manali_places.csv")

print(f"Dataset loaded successfully! ✅")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Dataset loaded successfully! ✅
Rows: 20
Columns: 9

In [3]:
df.head()

,place_id,name,address,country,latitude,longitude,rating,reviews,category
0,ChIJPeVowAaIBDkRnIfuPkskqi0,Hadimba Devi Temple,"Regency Road, Siyal Rd, Siyal, Manali, Himacha...",India,32.248353,77.181573,4.6,49688,Tourist attraction
1,ChIJ3VQyL0WHBDkR4Uml16nJto8,Old Manali snow point,"65XJ+J2W, Hadimba Temple Path, Old Manali, Man...",India,32.249112,77.180076,4.6,428,Tourist attraction
2,ChIJk9K3np2HBDkRS4FxsgYCMKI,Nehru Kund,"Bashisht, Himachal Pradesh 175103, India",India,32.285982,77.179824,4.4,7767,Tourist attraction
3,ChIJJSBNlWOJBDkRkmyIuy0OvGE,Kullu Manali River rafting,"65VQ+7MF, Siyal, Manali, Himachal Pradesh 1751...",India,32.243187,77.189176,4.5,88,Tourist attraction
4,ChIJHZ3eboyHBDkRBLrRpkcXmO4,Jogini Falls,"On water fall way V.P.O.-Vashist 5 km.from, Ma...",India,32.275076,77.188146,4.6,10842,Tourist attraction

In [4]:
print("Shape:", df.shape)
print("Rows:", len(df))
print("Columns:", len(df.columns))

Shape: (20, 9)
Rows: 20
Columns: 9

In [5]:
print(df.columns.tolist())

['place_id', 'name', 'address', 'country', 'latitude', 'longitude', 'rating', 'reviews', 'category']

In [6]:
df.dtypes

place_id         str
name             str
address          str
country          str
latitude     float64
longitude    float64
rating       float64
reviews        int64
category         str
dtype: object

In [7]:
missing = df.isnull().sum().sort_values(ascending=False)
missing

place_id     0
name         0
address      0
country      0
latitude     0
longitude    0
rating       0
reviews      0
category     0
dtype: int64

In [8]:
missing_percent = (df.isnull().mean() * 100).round(2).sort_values(ascending=False)
missing_percent

place_id     0.0
name         0.0
address      0.0
country      0.0
latitude     0.0
longitude    0.0
rating       0.0
reviews      0.0
category     0.0
dtype: float64

In [9]:
duplicate_count = df.duplicated().sum()
print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [10]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
place_id,20,20,ChIJPeVowAaIBDkRnIfuPkskqi0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
name,20,20,Hadimba Devi Temple,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
address,20,19,"65VQ+7MF, Siyal, Manali, Himachal Pradesh 1751...",2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,20,1,India,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,20.0,NaN,NaN,NaN,32.255111,0.02933,32.206785,32.242193,32.246274,32.256545,32.336362
longitude,20.0,NaN,NaN,NaN,77.188172,0.012963,77.168016,77.181199,77.18835,77.189231,77.225175
rating,20.0,NaN,NaN,NaN,4.505,0.198614,3.9,4.475,4.55,4.6,4.8
reviews,20.0,NaN,NaN,NaN,4397.25,11173.236792,11.0,85.0,283.5,3679.75,49688.0
category,20,1,Tourist attraction,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df[["name", "rating", "reviews"]].sort_values(
    by=["rating", "reviews"],
    ascending=[False, False]
).head(10)

                          name  rating  reviews
10               Kharma valley     4.8      143
14      Baror Parsha Waterfall     4.7      489
15       Old Manali View point     4.7       44
0          Hadimba Devi Temple     4.6    49688
4                 Jogini Falls     4.6    10842
1        Old Manali snow point     4.6      428
8   Lama Dugh Trek Start Point     4.6      297
12         Shiv Mahadev Temple     4.6      270
6            Manali View Point     4.6       87
11     Mini Switzerland Manali     4.6       79

In [12]:
df[["name", "rating", "reviews"]].sort_values(
    by="reviews",
    ascending=False
).head(10)

                          name  rating  reviews
0          Hadimba Devi Temple     4.6    49688
4                 Jogini Falls     4.6    10842
5      Van Vihar National Park     4.2     9050
2                   Nehru Kund     4.4     7767
19               Manali Bazaar     4.3     3991
18            Gulaba Viewpoint     4.5     3576
7            Rahala Waterfalls     4.5      797
14      Baror Parsha Waterfall     4.7      489
1        Old Manali snow point     4.6      428
8   Lama Dugh Trek Start Point     4.6      297

In [13]:
print("Unique categories:")
print(df["category"].dropna().unique())

print("\nCategory counts:")
print(df["category"].value_counts(dropna=False))

Unique categories:
<StringArray>
['Tourist attraction']
Length: 1, dtype: str

Category counts:
category
Tourist attraction    20
Name: count, dtype: int64

In [14]:
important_columns = [
    "name", "latitude", "longitude", "rating", "reviews", "category"
]

df[df[important_columns].isnull().any(axis=1)][important_columns]

Empty DataFrame
Columns: [name, latitude, longitude, rating, reviews, category]
Index: []

In [15]:
df[["name", "latitude", "longitude"]].head(10)

                         name   latitude  longitude
0         Hadimba Devi Temple  32.248353  77.181573
1       Old Manali snow point  32.249112  77.180076
2                  Nehru Kund  32.285982  77.179824
3  Kullu Manali River rafting  32.243187  77.189176
4                Jogini Falls  32.275076  77.188146
5     Van Vihar National Park  32.239113  77.189089
6           Manali View Point  32.233835  77.187359
7           Rahala Waterfalls  32.336362  77.218365
8  Lama Dugh Trek Start Point  32.248903  77.175013
9          Atal Bihari statue  32.245671  77.189757

In [16]:
print("Rating min:", df["rating"].min())
print("Rating max:", df["rating"].max())
print("Reviews min:", df["reviews"].min())
print("Reviews max:", df["reviews"].max())
print("Latitude min/max:", df["latitude"].min(), df["latitude"].max())
print("Longitude min/max:", df["longitude"].min(), df["longitude"].max())

Rating min: 3.9
Rating max: 4.8
Reviews min: 11
Reviews max: 49688
Latitude min/max: 32.206785499999995 32.3363624
Longitude min/max: 77.1680161 77.2251751